name: Continuous-integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python and Install requirements
      uses: ./.github/actions/python-setup
    - name: Run pylint
      run: pylint src